### ISSUE TITLE
Monkeyfinder application for running per latest branch 

### ISSUE THREAD

**Issue by akoranteng** [dotnet-presentations/xamarin.forms-workshop#2]
James,
 
I am running into issues testing out the latest branch from the link above: https://github.com/dotnet-presentations/xamarin.forms-workshop/. For the latest changes you implemented by removing the specific line outlined in the README.md file, The MainPage is not launching, it appears stuck. 
Also for the home screen, are we supposed to be seeing the exclamation mark.
My observations are from both the finish folder and new features folder.
The previous branch we hd 0n 01/28/2021,thethe search feature was working, but now is not happening.
Can you check on your end. Se attached screenshots.
![Screen Shot 2022-02-01_Main_Branch_StartPage](https://user-images.githubusercontent.com/13998322/152020739-3c4c08df-318c-47ac-8994-3a818e80a328.png)
![Screen Shot 2022-02-01_SearchButtonClicked](https://user-images.githubusercontent.com/13998322/152020741-d3f9b1c7-64ba-4a09-83aa-380c4a932119.png)

Regards
Alex.

**Comment by akoranteng** [comment]
James,

I think the reason the MainPage is not loading is that when the call to the Json file is returned from the HttpClient method, the url cannot be found because location pointers changed.  My observation is that when I click on the url link shown on line#41 as per attached screenshot for the MonkeysViewModel, it says the link has moved , See attached screenshot. We are getting this error across the board, for all past versions of this MonkeyApp I found in my backup folders as per attached. Let me know your thoughts. This page used to load few days ago.
![Screen Shot 2022-02-01 at 7 46 41 PM](https://user-images.githubusercontent.com/13998322/152076535-8c65afe8-4a91-4916-abee-0e1274f602bb.png)
![Screen Shot 2022-02-01 at 7 44 37 PM](https://user-images.githubusercontent.com/13998322/152076586-efa79702-881c-4999-b803-15d38dab66e9.png)
![Screen Shot 2022-02-01 at 7 43 44 PM](https://user-images.githubusercontent.com/13998322/152076599-163974f0-d616-4a21-9a9b-b4802acb8995.png)

Thanks
Alex.
.

**Comment by jamesmontemagno** [comment]
Fixed it up. They updated my backend, and the redirects weren't updated. Good now ;)
